### ISSUE TITLE
有人尝试过制作docker镜像并且运行成功吗？

### ISSUE THREAD

**Issue by tertiozhang** [padlocal/wechaty-puppet-padlocal-demo#21]
我可以在本地运行这个项目，现在想制作docker镜像并且放到云端运行，在运行docker镜像的时候，gRPC出错，导致登录不成功，错误信息如下：

01:11:39 INFO 
      ============================================================
       Welcome to Wechaty PadLocal puppet!

       - puppet-padlocal version: 1.20.1
       - padlocal-ts-client version: 0.5.3
      ============================================================
     
01:11:39 INFO [PadLocalDemo] started.
01:11:39 INFO [PuppetPadlocal] start login with type: QrLogin
01:11:40 ERR [Request] [tid:d744e852], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:d744e852] wechat request io error
01:11:40 WARN [LongLink] [182.50.10.168:80] close connection on error,IOError: long link init failed: [tid:d744e852] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d744e852] wechat request io error
01:11:40 WARN [LongLink] longlink reconnect [1] after delay:1000ms
VError: [tid:d744e852] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d744e852] wechat request io error
    at Request._failAllPendingRequest (/app/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (/app/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:692:18)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /app/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by jackchang1025** [comment]
我也是，在本地使用 node16 构建的镜像，安装运行报错：
![image](https://github.com/padlocal/wechaty-puppet-padlocal-demo/assets/71494064/edafe572-9fde-49a7-9f5b-baccb20745e6)

![image](https://github.com/padlocal/wechaty-puppet-padlocal-demo/assets/71494064/4b8d847d-0e35-49e8-9434-1cf4990f2655)

查看 [wechaty](https://wechaty.js.org/docs/puppet-services/padlocal) 文档说要配置阿里云虚拟机，是不是不能在本地运行，感觉文档真的多乱杂，看的真痛苦
