### ISSUE TITLE
扫码登录以后报错：你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面

### ISSUE THREAD

**Issue by wanshichen716** [padlocal/wechaty-puppet-padlocal-demo#25]
19:41:14 INFO [PadLocalDemo] onScan: Scanned(3)
19:41:30 INFO [PadLocalDemo] onScan: Confirmed(4)
19:41:30 ERR [Request] [tid:d4b09200], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:d4b09200] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
19:41:30 ERR start client failed: VError: [tid:d4b09200] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:d4b09200] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
    at Request._failAllPendingRequest (E:\game\wechaty-puppet-padlocal-demo\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (E:\game\wechaty-puppet-padlocal-demo\node_modules\padlocal-client-ts\src\Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:524:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (E:\game\wechaty-puppet-padlocal-demo\node_modules\@grpc\grpc-js\src\client.ts:706:18)
    at Object.onReceiveStatus (E:\game\wechaty-puppet-padlocal-demo\node_modules\@grpc\grpc-js\src\client-interceptors.ts:419:48)
    at E:\game\wechaty-puppet-padlocal-demo\node_modules\@grpc\grpc-js\src\resolving-call.ts:163:24
    at processTicksAndRejections (node:internal/process/task_queues:85:11)
19:41:32 INFO [PuppetPadlocal] start login with type: QrLogin
19:41:33 INFO [PadLocalDemo] onScan: Waiting(2)

**Comment by alileex** [comment]
bro，搞定这个问题了吗

**Comment by wanshichen716** [comment]
@alileex 没，这个已经不维护了，说是集体跑路

**Comment by wanglei158** [comment]
我申请的7天token  现在看来就是个笑话呀， 还好没花钱买
