### ISSUE TITLE
TSError: File '@chatie/tsconfig' not found

### ISSUE THREAD

**Issue by suntong** [padlocal/wechaty-puppet-padlocal-demo#3]
```
$ ts-node main.ts
/usr/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@chatie/tsconfig' not found.

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:517:19)
    at create (/usr/lib/node_modules/ts-node/src/index.ts:528:36)
    at Object.register (/usr/lib/node_modules/ts-node/src/index.ts:410:19)
    at main (/usr/lib/node_modules/ts-node/src/bin.ts:151:19)
    at Object.<anonymous> (/usr/lib/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

$ cat tsconfig.json 
{
  "extends": "@chatie/tsconfig",
  "compilerOptions": {
    "outDir": "dist",
  },
  "exclude": [
    "node_modules/",
    "dist/",
    "tests/fixtures/",
  ],
  "include": [
    "app/**/*.ts",
    "bin/*.ts",
    "bot/**/*.ts",
    "examples/**/*.ts",
    "scripts/**/*.ts",
    "src/**/*.ts",
    "tests/**/*.spec.ts",
  ],
}
```

I'm new to TypeScript. What's wrong with above? where can I get a copy of file '@chatie/tsconfig'? thx

The `main.ts` is just from this repo.

**Comment by suntong** [comment]
```
rm tsconfig.json

$ tsc --init --target ES6
message TS6071: Successfully created a tsconfig.json file.
```

Fixed the problem.
